spring:
  datasource:
    url: jdbc:tc:postgresql:18-alpine:///cashgrid_test
    username: test
    password: test

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    clean-disabled: false

logging:
  level:
    com.erenalyoruk.cashgrid: INFO
    org.testcontainers: WARN

app:
  jwt:
    secret: cashgrid-test-secret-key-must-be-at-least-32-characters-long
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

  rate-limit:
    default-capacity: 1000
    default-refill-tokens: 1000
    default-refill-seconds: 1
    auth-capacity: 1000
    auth-refill-tokens: 1000
    auth-refill-seconds: 1
